name: VCMI Mods

on:
  push:
    branches:
      - develop
  pull_request:
    paths:
      - "**.json"
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  check_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"
  validate_mod_json:
    needs: check_json
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Validate mod json
        run: |
          python3 .github/validate_mod_json.py
  update_size:
    needs: check_json
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Update size
        run: |
          python3 .github/update_size.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update sizes
          add: '*.json'
