name: VCMI Mods

on:
  push:
    branches:
      - develop
  pull_request:
    paths:
      - "**.json"
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  validate_json:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python environment
        run: sudo apt update && sudo apt install -y python3 python3-pip
      - name: Install jstyleson
        run: pip3 install jstyleson
      - name: Validate json
        run: python3 .github/validate_json.py

  validate_mod_json:
    needs: validate_json
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Install jstyleson
        run: pip3 install jstyleson
      - name: Validate mod json
        run: python3 .github/validate_mod_json.py

  update_size:
    needs: validate_json
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install jstyleson
        run: pip3 install jstyleson
      - name: Update size
        run: python3 .github/update_size.py

      - name: Determine branch and switch
        id: branch_info
        run: |
          if [ -z "$GITHUB_HEAD_REF" ]; then
            branch_name=$(git symbolic-ref --short HEAD)
          else
            branch_name=$GITHUB_HEAD_REF
          fi
          echo "branch_name=$branch_name" >> $GITHUB_ENV
          echo "Switched to branch: $branch_name"

      - name: Commit changes to the correct branch
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update sizes
          add: '*.json'
          push: --force
